version: '2'

services:
    nginx:
        container_name: nginx
        restart: always
        image: nginx:1.23-alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/app/django_static
    server:
        container_name: server
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /app/docker/backend/server-entrypoint.sh
        volumes:
            - static_volume:/django_static
        expose:
            - 8000     
        environment:
            DEBUG: "True"
            DJANGO_DB: postgresql
            POSTGRES_HOST: db
            POSTGRES_NAME: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_PORT: 5432
    db:
        container_name: db
        image: postgres:13.0-alpine
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        expose:
            - 5432
    test_db:
        container_name: test_db
        image: postgres:13.0-alpine
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/test_data/
        environment:
            POSTGRES_DB: test_postgres
            POSTGRES_USER: test_postgres
            POSTGRES_PASSWORD: test_postgres
        expose:
            - 5433
    
volumes:
    static_volume: {}
    postgres_data: {}